version: '3.8'

services:
  credit-postgres:
    image: postgres:16-alpine
    container_name: credit-postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=credit_assignment_db
      - POSTGRES_USER=platform_user
      - POSTGRES_PASSWORD=platform_password
    volumes:
      - postgres_master_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U platform_user -d credit_assignment_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  credit-redis:
    image: redis:7-alpine
    container_name: credit-redis-cache
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_master_data:
